spring:
  datasource:
    url: jdbc:mysql://139.196.192.223:3306/ROBOTS
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: Test123456@
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  thymeleaf:
    cache: false # 这个开发配置为false，避免改了模板还要重启服务器
    prefix: classpath:/templates/ # 这个可以不配置，检查模板位置
    check-template-location: true
    suffix: .html
    encoding: UTF-8
  mail:
    host: smtp.163.com
    username: sgzmsrobots@163.com
    password: STTQGUTKEPOYTGIC #Qwer123456
  redis:
    database: 0
    host: 139.196.192.223
    port: 6379
    timeout: 2000s
    password: redis123
mybatis:
    mapperLocations: classpath:*/mapper/*.xml

server:
#  对外提供服务端口 生产使用21102
  port: 9527
  #log
logging:
    config: classpath:logback.xml
    path: /data/log
wx:
  mp:
    configs:
      - appId: wx474c0cdef087d8b8 #（一个公众号的appid）
        secret: 36746980a141d4f0166f0286b5170a28 #（公众号的appsecret）
        token: tttt111111 #（接口配置里的Token值）
        aesKey: 2z0CCeACB2BAmkwsroWgNUbJTJ4WdSFKjrKRei5BY0h #（接口配置里的EncodingAESKey值）
